apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: devopszms2024/search-milan:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mongo-search-secret
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: db-port
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: search-configmap
                  key: service-port
            - name: BOOKING_HOST
              valueFrom:
                configMapKeyRef:
                  name: search-configmap
                  key: booking-host
            - name: BOOKING_PORT
              valueFrom:
                configMapKeyRef:
                  name: search-configmap
                  key: booking-port

---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: backend
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
